# ==================================================================================================================
sky:
  helloWorld: <center><h1>Welcome to Auth app.</h1></center>

# SPRING setup
server:
  port: ${AUTH_PORT:9100}

spring:
  application:
    name: auth-service
  web:
    locale-resolver: accept_header
  mvc:
    dispatch-options-request: true

  security:
    user:
      name: ${SPRING_SECURITY_USER:XYZ}
      password: ${SPRING_SECURITY_PASS:XYZ}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: ${SHOW_SQL_QUERIES:false}
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Warsaw

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/sky}
    hikari:
      connection-timeout: 60000
      validation-timeout: 60000
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:Lukk1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: ${SPRING_DEBUG:INFO}
      hibernate: ${HIBERNATE_DEBUG:INFO}
