# ==================================================================================================================
# SPRING setup

server:
  port: ${NOTIFY_PORT:5554}

spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: false

logging:
  level:
    org:
      springframework:
        web: ${SPRING_DEBUG:INFO}
        messaging:
          simp:
            broker:
              SimpleBrokerMessageHandler: WARN
      apache:
        kafka:
          clients:
            consumer:
              ConsumerConfig: WARN

