language: java
sudo: required
services:
  - docker
after_success:
  - docker-compose rm -f
  - docker-compose build --no-cache
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker tag sky lukk17/sky
  - docker push lukk17/sky
  - docker images

deploy:
  provider: s3
  region: eu-west-2
  app: Sky
  env: Sky-env
  bucket: elasticbeanstalk-eu-west-2-564476143638
  skip_cleanup: true
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
