language: java
sudo: required
services:
  - docker
after_success:
  - docker docker-compose up --build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lukk17/sky