version: "3"
services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: sky
    depends_on:
      - "mysql"
    logging:
      driver: json-file
    expose:
      - 5555
    ports:
      - 5555:5555
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=Lukk1234
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=Lukk1234
      - MYSQL_DATABASE=sky
      - MYSQL_PASSWORD=Lukk1234
