
image:
  name: "quay.io/oauth2-proxy/oauth2-proxy:v7.4.0"
  imagePullPolicy: "IfNotPresent"

args:
  provider: "keycloak-oidc"
  emailDomain: "*"
  upstream: "file:///dev/null"
  httpAddress: "0.0.0.0:4180"
  cookieSecure: "false"
  oidcIssuerUrl: "https://keycloak.luksarna.com/realms/sky"
  insecureOidcAllowUnverifiedEmail: "true"
  redirectUrl: "https://skycloud.luksarna.com/oauth2/callback"
  setAuthorizationHeader: "true"
  scope: "openid email"
  setXauthrequest: "true"
  passAuthorizationHeader: "true"
  passAccessToken: "true"
  passHostHeader: "true"
  passUserHeaders: "true"
  passBasicAuth: "true"

secrets:
  clientIdKey: "keycloak-client-id"
  clientSecretKey: "keycloak-client-secret"
  cookieSecretKey: "keycloak-client-cookie-secret"
  secretName: "sky-secrets"

service:
  name: oauth2-proxy
  port: 4180

ingress:
  name: oauth2-ingress
  tls:
    secretName: dev-ssl-cert
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

  controller: "nginx"
  hosts:
    - host: skycloud.luksarna.com
      paths:
        - path: "/oauth2(/|$)(.*)"
          pathType: ImplementationSpecific
