# ==================================================================================================================
# SPRING setup

server:
  port: ${MESSAGE_PORT:5553}

spring:
  application:
    name: sky-message
  web:
    locale-resolver: accept_header
  mvc:
    dispatch-options-request: true
  security:
    user:
      name: ${SPRING_SECURITY_USER:XYZ}
      password: ${SPRING_SECURITY_PASS:XYZ}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: ${SHOW_SQL_QUERIES:false}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/sky}
    hikari:
      connection-timeout: 60000
      validation-timeout: 60000
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:Lukk1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

# expose actuator endpoints (* for all)
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: ${SPRING_DEBUG:INFO}
      hibernate: ${HIBERNATE_DEBUG:INFO}
