version: "3.9"

services:

  sky-booking:
    container_name: sky-booking
    build:
      dockerfile: ./sky-booking/docker/Dockerfile
      context: ../../
    networks:
      - sky-network
    restart: always
    expose:
      - 5555
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?${DB_PARAMS}
      - NAMING_SERVICE_URL=${NAMING_SERVICE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - SHOW_SQL_QUERIES=${SHOW_SQL_QUERIES}
      - SPRING_DEBUG=${SPRING_DEBUG}
      - HIBERNATE_DEBUG=${HIBERNATE_DEBUG}
      - SPRING_SECURITY_USER=${SPRING_SECURITY_USER}
      - SPRING_SECURITY_PASS=${SPRING_SECURITY_PASS}

  sky-notify:
    container_name: sky-notify
    build:
      dockerfile: ./sky-notify/docker/Dockerfile
      context: ../../
    networks:
      - sky-network
    restart: always
    expose:
      - 5554
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?${DB_PARAMS}
      - NAMING_SERVICE_URL=${NAMING_SERVICE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - SHOW_SQL_QUERIES=${SHOW_SQL_QUERIES}
      - SPRING_DEBUG=${SPRING_DEBUG}
      - HIBERNATE_DEBUG=${HIBERNATE_DEBUG}
      - SPRING_SECURITY_USER=${SPRING_SECURITY_USER}
      - SPRING_SECURITY_PASS=${SPRING_SECURITY_PASS}

  sky-offer:
    container_name: sky-offer
    build:
      dockerfile: ./sky-offer/docker/Dockerfile
      context: ../../
    networks:
      - sky-network
    restart: always
    expose:
      - 5552
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?${DB_PARAMS}
      - NAMING_SERVICE_URL=${NAMING_SERVICE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - SHOW_SQL_QUERIES=${SHOW_SQL_QUERIES}
      - SPRING_DEBUG=${SPRING_DEBUG}
      - HIBERNATE_DEBUG=${HIBERNATE_DEBUG}
      - SPRING_SECURITY_USER=${SPRING_SECURITY_USER}
      - SPRING_SECURITY_PASS=${SPRING_SECURITY_PASS}

  sky-message:
    container_name: sky-message
    build:
      dockerfile: ./sky-message/docker/Dockerfile
      context: ../../
    networks:
      - sky-network
    restart: always
    expose:
      - 5553
    ports:
      - "5553:5553"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?${DB_PARAMS}
      - NAMING_SERVICE_URL=${NAMING_SERVICE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - SHOW_SQL_QUERIES=${SHOW_SQL_QUERIES}
      - SPRING_DEBUG=${SPRING_DEBUG}
      - HIBERNATE_DEBUG=${HIBERNATE_DEBUG}
      - SPRING_SECURITY_USER=${SPRING_SECURITY_USER}
      - SPRING_SECURITY_PASS=${SPRING_SECURITY_PASS}

networks:
  sky-network:
    name: sky-network
