# Default values for sky-message.

name: "sky-message"
namespace: "default"

label:
  app: "sky-message"

replicaCount: 1

deployment:
  name: "sky-message-deployment"
  image:
    repository: "lukk17/sky-message"
    pullPolicy: "Always"
    tag: "v1.0.1-candidate-x01"
  container:
    name: "sky-message-container"
  env:
    spring:
      datasourceUrl: "jdbc:mysql://mysql-service:3306/sky"
      debug: "INFO"
      securityUser: "spring-security-user"
      securityPass: "spring-security-pass"
    hibernate:
      showSqlQueries: "false"
      debug: "INFO"
    mysql:
      user: "mysql-root-user"
      pass: "mysql-root-pass"

secret:
  name: "sky-secrets"

imagePullSecrets:
  - name: "docker-cred"

service:
  name: "sky-message-service"
  type: "ClusterIP"
  port: "5553"
  apiPrefix: "/msg/api"

ingress:
  service:
    name: "sky-message-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/api/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    tls:
      - hosts:
          - skycloud.luksarna.com
        secretName: dev-ssl-cert

    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/msg/api(/|$)(.*)"
            pathType: "ImplementationSpecific"
          - path: "/swagger-ui(/|$)(.*)"
            pathType: "ImplementationSpecific"

  swagger:
    name: "sky-message-swagger-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/swagger-ui/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    tls:
      - hosts:
          - skycloud.luksarna.com
        secretName: dev-ssl-cert

    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/msg/swagger-ui(/|$)(.*)"
            pathType: "ImplementationSpecific"

  swaggerResource:
    name: "sky-message-swagger-resources-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/v3/api-docs/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    tls:
      - hosts:
          - skycloud.luksarna.com
        secretName: dev-ssl-cert

    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/msg/v3/api-docs(/|$)(.*)"
            pathType: "ImplementationSpecific"

actuator:
  livenessProbe:
    path: "/actuator/health/liveness"
    initialDelaySeconds: "30"
    periodSeconds: "5"
    failureThreshold: "35"
  readinessProbe:
    path: "/actuator/health/readiness"
    initialDelaySeconds: "10"
    periodSeconds: "5"
    failureThreshold: "15"
