# Default values for sky-message.

name: "sky-message"

label:
  app: "sky-message"

replicaCount: 1

deployment:
  name: "sky-message-deployment"
  image:
    repository: "lukk17/sky-message"
    pullPolicy: "IfNotPresent"
    tag: "v2.0.0"
  container:
    name: "sky-message-container"
  env:
    spring:
      datasourceUrl: "jdbc:postgresql://postgres-service:5432/sky"
      debug: "INFO"
    hibernate:
      showSqlQueries: "false"
      debug: "INFO"
    postgres:
      user: "postgres-user"
      pass: "postgres-password"

secret:
  name: "sky-secrets"

imagePullSecrets:
  - name: "docker-cred"

service:
  name: "sky-message-service"
  type: "ClusterIP"
  port: "5553"
  apiPrefix: "/api/v1"

ingress:
  tls:
    secretName: ""

  service:
    name: "sky-message-ingress"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token, authorization"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    hosts:
      - host: ""
        paths:
          - path: "/api/v1/messages"
            pathType: "Prefix"

  swagger:
    name: "sky-message-swagger-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/swagger-ui$1$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/msg"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token, authorization"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    hosts:
      - host: ""
        paths:
          - path: "/msg/swagger-ui(/|[.]|$)(.*)"
            pathType: "ImplementationSpecific"

  swaggerResource:
    name: "sky-message-swagger-resources-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/v3/api-docs/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "/msg"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token, authorization"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    hosts:
      - host: ""
        paths:
          - path: "/msg/v3/api-docs(/|$)(.*)"
            pathType: "ImplementationSpecific"

oauth2:
  issuerUri: ""
  audience: "sky-backend"

crossOrigin:
  allowed: ""

actuator:
  startupProbe:
    path: "/actuator/health/liveness"
    periodSeconds: 5
    failureThreshold: 36
  livenessProbe:
    path: "/actuator/health/liveness"
    initialDelaySeconds: 0
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    path: "/actuator/health/readiness"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
