# Default values for sky-offer.

name: sky-notify
namespace: default

label:
  app: sky-notify

replicaCount: 1

deployment:
  name: sky-notify-deployment
  image:
    repository: lukk17/sky-notify
    pullPolicy: IfNotPresent
    tag: "1.0.2"
  container:
    name: sky-notify-container
  env:
    spring:
      debug: "INFO"
      securityUser: "spring-security-user"
      securityPass: "spring-security-pass"

secret:
  name: sky-secrets

imagePullSecrets:
  - name: docker-cred

service:
  name: sky-notify-service
  type: ClusterIP
  port: "5554"

oauth2:
  issuerUri: "https://keycloak.luksarna.com/realms/sky"
  audience: "sky-backend"

kafka:
  address: "kafka-service"
  port: "9092"

actuator:
  startupProbe:
    path: "/actuator/health/liveness"
    periodSeconds: 5
    failureThreshold: 36
  livenessProbe:
    path: "/actuator/health/liveness"
    initialDelaySeconds: 0
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    path: "/actuator/health/readiness"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
