version: "3"
services:
  sky:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: sky
    #    depends_on:
    #      - "mysql"
    logging:
      driver: json-file
    #      expose to other containers
    expose:
      - 5555
    #    port HOST:CONTAINER (exposing to host)
    ports:
      - 8080:5555
    environment:
      - MYSQL_HOST=sky.ccrunaygib3u.eu-west-2.rds.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_USER=rooty
      - MYSQL_PASS=Lukk1234

      #     ONLY FOR LOCAL TEST WITH LOCAL MYSQL INSTANCE:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - MYSQL_ROOT_PASSWORD=Lukk1234
#      - MYSQL_DATABASE=sky
#      - MYSQL_PASSWORD=Lukk1234
