---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=oidc
            - --email-domain="*"
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --cookie-secure=false
            - --oidc-issuer-url=https://lukk17.eu.auth0.com/
            - --insecure-oidc-allow-unverified-email=true
            - --redirect-url=http://sky.luksarna.com/oauth2/callback
            - --set-authorization-header=true
            - --scope=openid email
            - --set-xauthrequest=true
            - --pass-authorization-header=true
            - --set-authorization-header=true
            - --pass-access-token=true
            - --pass-host-header=true
            - --pass-user-headers=true
            - --pass-basic-auth=true
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: 9H4ckShWBYzA5gigTK0VnR1I1Hh7MHz0
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: g6B2jR-MXS_jWppT0MYg3GsyCZf7Zlgl6zhC1b3K7qAbc6p92uBQJYXaLRyv2b3c
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: SEEECRETXXXXXXXX

          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
