---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=oidc
            - --email-domain=*
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --cookie-secure=false
            - --oidc-issuer-url=https://lukk17.eu.auth0.com/
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: <clientid>
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: <secret>
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: SEEECRETXXXXXXXX

          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
