# ==================================================================================================================
# SPRING setup

server:
  port: 5552


spring:
  application:
    name: sky-offer
  web:
    locale-resolver: accept_header
  mvc:
    dispatch-options-request: true
  security:
    user:
      name: ${SPRING_SECURITY_USER:XYZ}
      password: ${SPRING_SECURITY_PASS:XYZ}
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: ${SHOW_SQL_QUERIES:false}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/sky?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw}
    hikari:
      connection-timeout: 60000
      validation-timeout: 60000
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:Lukk1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

# expose actuator endpoints (* for all)
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: ${SPRING_DEBUG:INFO}
      hibernate: ${HIBERNATE_DEBUG:INFO}

# ==================================================================================================================
# EUREKA setup

#for docker
eureka:
  client:
    service-url:
      defaultZone: ${NAMING_SERVICE_URL:http://host.docker.internal:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

# in docker sometimes there is problem with DNS resolving - that why ip addresses are better as names
  instance:
    preferIpAddress: true
