
image:
  name: "quay.io/oauth2-proxy/oauth2-proxy:v7.4.0"
  imagePullPolicy: "Always"

args:
  provider: "oidc"
  emailDomain: "*"
  upstream: "file:///dev/null"
  httpAddress: "0.0.0.0:4180"
  cookieSecure: "false"
  oidcIssuerUrl: "https://lukk17.eu.auth0.com/"
  insecureOidcAllowUnverifiedEmail: "true"
  redirectUrl: "http://sky.luksarna.com/oauth2/callback"
  setAuthorizationHeader: "true"
  scope: "openid email"
  setXauthrequest: "true"
  passAuthorizationHeader: "true"
  passAccessToken: "true"
  passHostHeader: "true"
  passUserHeaders: "true"
  passBasicAuth: "true"

service:
  port: 4180
