---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{  .Values.volume.claimName }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{  .Values.volume.storage }}
