# ==================================================================================================================
# SPRING setup

server:
  port: 8762

spring:
  application:
    name: zuul-service
  security:
    user:
      name: XYZ
      password: XYZ
  mvc:
    # location from http header
    locale-resolver: accept_header
    # for option request handling
    dispatch-options-request: true

# expose actuator endpoints (* for all)
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO

# ==================================================================================================================
# EUREKA setup

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    # change default link to service in eureka dashboard
    statusPageUrlPath: http://localhost:${server.port}/actuator


# ==================================================================================================================
#   Timeout settings

# Increase the Hystrix timeout to 60s (globally)
# important for docker - without this increased timeout there will be "Error during filtering"
# hystrix timeout 122001 to be more than Ribbon read and connect timeout, if not warning will be printed:
# The Hystrix timeout of 60000ms for the command auth-service is set lower than the combination of the Ribbon read and connect timeout.
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 242001
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


  # ==================================================================================================================
  # PATH mapping
zuul:
  host:
    # in correlation with above hystrix timeout configuration
    connect-timeout-millis: 10000
    socket-timeout-millis: 1000000
  routes:
    sky-offer:
      path: /offer/**
      service-id: sky-offer
    sky-message:
      path: /message/**
      service-id: sky-message
    auth-service:
      path: /auth/**
      service-id: auth-service
  # Map path to auth service
    login:
      path: /login
      service-id: auth-service
  # If request is "/offer/view/1", sky-offer service will get "/view/1".
  # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
      strip-prefix: false
    register:
      path: /register
      service-id: auth-service
      strip-prefix: false
    # Exclude authorization from sensitive headers
    sensitive-headers: Cookie,Set-Cookie
