---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: auth
          image: lukk17/sky-auth
          ports:
            - containerPort: 9100
          env:
            - name: AUTH_PORT
              value: "9100"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/sky
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysqlrootPass
                  name: skysecrets
            - name: SPRING_DEBUG
              value: "INFO"
            - name: HIBERNATE_DEBUG
              value: "INFO"
            - name: SHOW_SQL_QUERIES
              value: "false"
            - name: SPRING_SECURITY_USER
              valueFrom:
                secretKeyRef:
                  key: springsecurityuser
                  name: skysecrets
            - name: SPRING_SECURITY_PASS
              valueFrom:
                secretKeyRef:
                  key: springsecuritypass
                  name: skysecrets