---
apiVersion: v1
kind: Secret
metadata:
#  needs to be lowercase !
  name: sky-secrets
  namespace: default
type: Opaque
data:
  mysql-root-user: XXX
  mysql-root-pass: XXX
  mysql-username: XXX
  mysql-password: XXX
  spring-security-user: XXX
  spring-security-pass: XXX
  keycloak-user: XXX
  keycloak-pass: XXX
  postgres-pass: XXX
  postgres-user: XXX
  auth0-client-id: XXX
  auth0-client-secret: XXX
  auth0-client-cookie-secret: XXX

