CREATE TABLE IF NOT EXISTS booking (
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    offer_id     VARCHAR(255) NOT NULL,
    booked_date  DATE         NOT NULL,
    booking_user VARCHAR(255) NOT NULL,
    owner_email  VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS booking_event (
    id              BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booking_id      BIGINT      NOT NULL,
    sequence_number INT         NOT NULL,
    event_type      VARCHAR(32) CHECK (event_type IN ('BOOKED', 'CANCELED', 'RESERVED')),
    payload         TEXT,
    timestamp       TIMESTAMP(6),
    PRIMARY KEY (id)
);
