apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
#   ReadWriteOnce mean only single node can have access
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi