apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            #            name from metadata section of database-persistent-volume-claim.yaml
            claimName: database-persistent-volume-claim
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            #            default place where mysql is saving data
            - mountPath: /var/lib/mysql
              #              name of volume specified in spec.volumes section
              name: mysql-storage
#              some db like postgres need additional parameter of subPath
#              subPath: postgres
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
#                  from secret.yaml data section
                  key: mysqlrootPass
#                  from secret.yaml metadata.name section
                  name: skysecrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysqlusername
                  name: skysecrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysqlpassword
                  name: skysecrets
