# Production-environment overlay for keycloak.
#
# Apply on top of values.yaml:
#   helm upgrade --install keycloak ./config/k8s/helm/infra/keycloak -f ./config/k8s/helm/infra/keycloak/values-prod.yaml

hostname: "keycloak.luksarna.com"

ingress:
  tls:
    secretName: sky-tls-cert
  hosts:
    - host: "keycloak.luksarna.com"
      paths:
        - path: "/"
          pathType: "Prefix"
