# Default values for sky-booking.

name: "sky-booking"
namespace: "default"

label:
  app: "sky-booking"

replicaCount: 1

deployment:
  name: "sky-booking-deployment"
  image:
    repository: "lukk17/sky-booking"
    pullPolicy: "IfNotPresent"
    tag: "1.0.2"
  container:
    name: "sky-booking-container"
  env:
    spring:
      datasourceUrl: "jdbc:postgresql://postgres-service:5432/sky"
      debug: "INFO"
      securityUser: "spring-security-user"
      securityPass: "spring-security-pass"
    hibernate:
      showSqlQueries: "false"
      debug: "INFO"
    postgres:
      user: "postgres-user"
      pass: "postgres-password"

secret:
  name: "sky-secrets"

imagePullSecrets:
  - name: "docker-cred"

service:
  name: "sky-booking-service"
  type: "ClusterIP"
  port: "5555"
  apiPrefix: "/booking/api"

ingress:
  tls:
    secretName: dev-ssl-cert

  service:
    name: "sky-booking-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/api/v1/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token, authorization"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/booking/api(/|$)(.*)"
            pathType: "ImplementationSpecific"
  swagger:
    name: "sky-booking-swagger-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/swagger-ui/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token, authorization"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/booking/swagger-ui(/|$)(.*)"
            pathType: "ImplementationSpecific"

  swaggerResource:
    name: "sky-booking-swagger-resources-ingress"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/v3/api-docs/$2"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token, authorization"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "90"

    controller: "nginx"
    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/booking/v3/api-docs(/|$)(.*)"
            pathType: "ImplementationSpecific"

oauth2:
  issuerUri: "https://keycloak.luksarna.com/realms/sky"
  audience: "sky-backend"

kafka:
  address: "kafka-service"
  port: "9092"

offerService:
  hostname: "http://sky-offer-service.default.svc.cluster.local"
  port: "5552"

actuator:
  startupProbe:
    path: "/actuator/health/liveness"
    periodSeconds: 5
    failureThreshold: 36
  livenessProbe:
    path: "/actuator/health/liveness"
    initialDelaySeconds: 0
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    path: "/actuator/health/readiness"
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
