# Production-environment overlay for sky-booking.
#
# Apply on top of values.yaml:
#   helm upgrade --install sky-booking ./config/k8s/helm/service/sky-booking -f ./config/k8s/helm/service/sky-booking/values-prod.yaml

deployment:
  image:
    pullPolicy: "IfNotPresent"

oauth2:
  issuerUri: "https://keycloak.luksarna.com/realms/sky"

ingress:
  tls:
    secretName: sky-tls-cert

  service:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/booking/api(/|$)(.*)"
            pathType: "ImplementationSpecific"

  swagger:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/booking/swagger-ui(/|$)(.*)"
            pathType: "ImplementationSpecific"

  swaggerResource:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://skycloud.luksarna.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://skycloud.luksarna.com/oauth2/start"
    hosts:
      - host: "skycloud.luksarna.com"
        paths:
          - path: "/booking/v3/api-docs(/|$)(.*)"
            pathType: "ImplementationSpecific"
