---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-notify-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
        - name: sky-notify-container
          image: lukk17/sky-notify:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5554
          env:
            - name: NOTIFY_PORT
              value: '5554'
            - name: KAFKA_ADDRESS
              value: 'kafka-service'
            - name: KAFKA_PORT
              value: '9092'
            - name: SPRING_DEBUG
              value: 'INFO'
            - name: SPRING_SECURITY_USER
              valueFrom:
                secretKeyRef:
                  key: spring-security-user
                  name: sky-secrets
            - name: SPRING_SECURITY_PASS
              valueFrom:
                secretKeyRef:
                  key: spring-security-pass
                  name: sky-secrets
