---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE sky;
    CREATE DATABASE kong;
    CREATE DATABASE konga;
    CREATE USER kong WITH ENCRYPTED PASSWORD 'kong';
    GRANT ALL PRIVILAGES ON DATABASE kong TO kong;
