ingress:
  enabled: true
  controller: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "90"
  hosts:
    - host: "s3.localhost"
      paths:
        - path: "/"
          pathType: "Prefix"
