apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sky-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: request-transformer,oidc    #keycloak authentication
#    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: kong
  rules:
    - host: sky.localhost
      http:
        paths:
          - path: /offer
            pathType: Prefix
            backend:
              service:
                name: sky-offer-service
                port:
                  number: 5552
          - path: /message
            pathType: Prefix
            backend:
              service:
                name: sky-message-service
                port:
                  number: 5553
