# ==================================================================================================================
# SPRING setup

server:
  port: 8761

spring:
  application:
    name: eureka-service

# expose actuator endpoints (* for all)
management:
  endpoints:
    web:
      exposure:
        include: "*"

# ==================================================================================================================
# EUREKA setup

#   eureka by default will register itself as a client. So, we need to set it to false.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761
    register-with-eureka: false
    fetch-registry: false