# ==================================================================================================================
# SPRING setup

server:
  port: 8761

spring:
  application:
    name: eureka-service

# expose actuator endpoints (* for all)
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO
# ==================================================================================================================
# EUREKA setup

#   eureka by default will register itself as a client. So, we need to set it to false.
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://host.docker.internal:8761/eureka}
    register-with-eureka: false
    fetch-registry: false

  # in docker sometimes there is problem with DNS resolving - that why ip addresses are better as names
  instance:
    preferIpAddress: true