---
apiVersion: v1
kind: Service
metadata:
  name: sky-booking-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: 5555

  selector:
    component: booking
