CREATE TABLE IF NOT EXISTS message (
    id             BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    text           TEXT         NOT NULL,
    created_time   TIMESTAMP(6),
    is_read        BOOLEAN      NOT NULL DEFAULT FALSE,
    receiver_email VARCHAR(255) NOT NULL,
    sender_email   VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
