---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
    - name: session
      port: {{ .Values.session.port }}
      protocol: TCP
      targetPort: {{ .Values.session.port }}
  selector:
    k8s-app: oauth2-proxy
