---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
    - port: {{  .Values.service.port }}
      targetPort: {{  .Values.service.port }}

  selector:
    component: mysql
