---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: mysql-service
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{  .Values.volume.claimName }}
        - name: mysql-initdb
          configMap:
            name: {{ .Values.volume.configMap.name }}
      containers:
        - name: mysql
          image: {{  .Values.image.name }}
          imagePullPolicy: {{  .Values.image.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          ports:
            - containerPort: {{  .Values.service.port }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          startupProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            periodSeconds: 5
            failureThreshold: 24
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 0
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-pass
                  name: sky-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-username
                  name: sky-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: sky-secrets
