---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  keycloak.override: |
    rewrite name keycloak.127.0.0.1.nip.io ingress-nginx-controller.ingress-nginx.svc.cluster.local
