---
apiVersion: v1
kind: Secret
metadata:
  name: sky-secrets
  namespace: default
type: Opaque
stringData:
  postgres-user: "postgres"
  postgres-password: "local"
  s3-access-key: "root"
  s3-secret-key: "localdev"
  keycloak-admin: "admin"
  keycloak-admin-password: "admin"
  keycloak-db-user: "keycloak_user"
  keycloak-db-password: "keycloak_pass"
  keycloak-client-id: "sky-backend"
  keycloak-client-secret: "dev-only-change-in-prod"
  keycloak-client-cookie-secret: "local-dev-cookie-secret-32-bytes"
