---
apiVersion: v1
data:
#  base64 coding
  secretkey: QUxvc3VSS2VOVGtXZys0a2R1Snk=
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.80-192.168.1.90
  autoAssign: false
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgpadvertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
---
